name: example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  modal_bottom_sheet:
    path: '../'
  url_launcher: ^6.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
   - assets/